### ISSUE TITLE
Imgur Community Extension issues

### ISSUE THREAD

**Issue by ShereeBrown** [chrhasse/imgur-Extension#2]
It trying to connect it  not please fix these issues
![Screenshot 2021-06-30 080952](https://user-images.githubusercontent.com/8306345/123873983-c0464400-d97a-11eb-9856-1dddf76ebeaf.jpg)
please fix it

**Comment by ShereeBrown** [comment]
still, happen again got an error, error FIX THESE ERROR or I do not use that imgur community anymore this Extension is rubbish now fix it now alright now or I not happy

**Comment by ShereeBrown** [comment]
It never works with google chrome all other browsers are fine like firefox why are Imgur community extensions not connected with google chrome my Imgur account should be connected it

**Comment by chrhasse** [comment]
My apologies for replying so late, I wasn't being notified of issues by email and I hadn't checked the repository. This is almost definitely a result of rate limiting from imgur and unfortunately there is no fix available for me short of paying absurd amounts of money for a project I make no money on. There is a fix you can do detailed on [the wiki](https://github.com/chrhasse/imgur-Extension/wiki#using-custom-api-keys)

**Comment by ShereeBrown** [comment]
it not work, I am not happy, I can't fix this is pathetic, okay it works on firefox it does not work on chrome
